[package]
name = "slint-menubar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfd = "0.15.2"
slint = "1.9.2"

[build-dependencies]
slint-build = "1.9.2"
